### PR TITLE
Nether Update Compatibility

### PR DESCRIPTION
**Pull request by Aikoyori**
I fixed it but it's super jank idk how to fix the rest help

### CODE REVIEW

**Comment by Aikoyori** [comment]
was supposed to pull req on my fork lmao

**Comment by qixils** [comment]
huh

**Comment by qixils** [comment]
do you still need help/want to merge? i can look into fixing whatever lol

**Comment by Aikoyori** [comment]
lol it wasn't working for 1.16 so I tried my best to fix it the changes I made still suck because I am bad at Python

**Pull request closed without merging**
